In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('upi_transactions_2024.csv')

In [ ]:
df

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,TXN0000249996,2024-11-08 22:41:43,Recharge,Food,373,SUCCESS,36-45,26-35,Telangana,ICICI,HDFC,iOS,5G,0,22,Friday,0
249996,TXN0000249997,2024-12-15 02:58:03,P2P,Utilities,2025,SUCCESS,36-45,26-35,Rajasthan,HDFC,Yes Bank,Android,5G,0,2,Sunday,1
249997,TXN0000249998,2024-11-27 16:33:25,P2P,Food,468,SUCCESS,26-35,18-25,West Bengal,ICICI,ICICI,Android,4G,0,16,Wednesday,0
249998,TXN0000249999,2024-01-05 13:31:30,Recharge,Healthcare,284,SUCCESS,18-25,36-45,Andhra Pradesh,Axis,ICICI,iOS,4G,0,13,Friday,0
249999,TXN0000250000,2024-01-17 15:23:07,P2P,Entertainment,531,SUCCESS,18-25,26-35,Telangana,Axis,Yes Bank,Android,4G,0,15,Wednesday,0

Total transactions divided by types

In [ ]:
df['transaction type'].value_counts()

transaction type
P2P             112445
P2M              87660
Bill Payment     37368
Recharge         12527
Name: count, dtype: int64

In [ ]:
df.head(5)

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

In [ ]:
df['device_type'].value_counts()

device_type
Android    187777
iOS         49613
Web         12610
Name: count, dtype: int64

In [ ]:
df['transaction_status'].value_counts()

transaction_status
SUCCESS    237624
FAILED      12376
Name: count, dtype: int64

In [ ]:
df['network_type'].value_counts()

network_type
4G      149813
5G       62582
WiFi     25134
3G       12471
Name: count, dtype: int64

In [ ]:
df['day_of_week'].value_counts()

day_of_week
Monday       36495
Sunday       36003
Wednesday    35700
Tuesday      35540
Friday       35496
Thursday     35432
Saturday     35334
Name: count, dtype: int64

In [ ]:
df['sender_state'].value_counts()

sender_state
Maharashtra       37427
Uttar Pradesh     30125
Karnataka         29756
Tamil Nadu        25367
Delhi             24870
Telangana         22435
Gujarat           20061
Andhra Pradesh    20006
Rajasthan         19981
West Bengal       19972
Name: count, dtype: int64

In [ ]:
df['sender_age_group'].value_counts()

sender_age_group
26-35    87432
36-45    62873
18-25    62345
46-55    24841
56+      12509
Name: count, dtype: int64

In [ ]:
df['receiver_age_group'].value_counts()

receiver_age_group
26-35    87864
18-25    62611
36-45    62151
46-55    24823
56+      12551
Name: count, dtype: int64

In [ ]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

In [ ]:
fraud_payment = df['fraud_flag'].value_counts()
fraud_payment

fraud_flag
0    249520
1       480
Name: count, dtype: int64

In [ ]:
print(df[df['fraud_flag']==1]['network_type'].value_counts())

network_type
4G      282
5G      115
WiFi     59
3G       24
Name: count, dtype: int64

In [ ]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

Success transaction rate for each device type individually

In [ ]:
df.groupby('device_type')['fraud_flag'].value_counts()

device_type  fraud_flag
Android      0             187413
             1                364
Web          0              12584
             1                 26
iOS          0              49523
             1                 90
Name: count, dtype: int64

For each device_type, show % of Success and Failed transactions.

In [ ]:
(df.groupby('device_type')['transaction_status'].value_counts(normalize=True)* 100)

device_type  transaction_status
Android      SUCCESS               95.059033
             FAILED                 4.940967
Web          SUCCESS               94.845361
             FAILED                 5.154639
iOS          SUCCESS               95.065809
             FAILED                 4.934191
Name: proportion, dtype: float64

In [ ]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

In [ ]:
df.drop('timestamp', axis = 1)

,transaction id,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,TXN0000249996,Recharge,Food,373,SUCCESS,36-45,26-35,Telangana,ICICI,HDFC,iOS,5G,0,22,Friday,0
249996,TXN0000249997,P2P,Utilities,2025,SUCCESS,36-45,26-35,Rajasthan,HDFC,Yes Bank,Android,5G,0,2,Sunday,1
249997,TXN0000249998,P2P,Food,468,SUCCESS,26-35,18-25,West Bengal,ICICI,ICICI,Android,4G,0,16,Wednesday,0
249998,TXN0000249999,Recharge,Healthcare,284,SUCCESS,18-25,36-45,Andhra Pradesh,Axis,ICICI,iOS,4G,0,13,Friday,0
249999,TXN0000250000,P2P,Entertainment,531,SUCCESS,18-25,26-35,Telangana,Axis,Yes Bank,Android,4G,0,15,Wednesday,0

In [ ]:
df.groupby('sender_state')['transaction_status'].value_counts(normalize = True)*100

sender_state    transaction_status
Andhra Pradesh  SUCCESS               95.001500
                FAILED                 4.998500
Delhi           SUCCESS               95.026136
                FAILED                 4.973864
Gujarat         SUCCESS               95.219580
                FAILED                 4.780420
Karnataka       SUCCESS               95.137115
                FAILED                 4.862885
Maharashtra     SUCCESS               95.078419
                FAILED                 4.921581
Rajasthan       SUCCESS               95.205445
                FAILED                 4.794555
Tamil Nadu      SUCCESS               94.883116
                FAILED                 5.116884
Telangana       SUCCESS               95.293069
                FAILED                 4.706931
Uttar Pradesh   SUCCESS               94.781743
                FAILED                 5.218257
West Bengal     SUCCESS               94.957941
                FAILED                 5.042059
Name: proportion, dtype: float64

 To find how many frauds happened per state.

In [ ]:
fraud_counts = df[df['fraud_flag']==1].groupby('sender_state').size()
sorted_fraud_counts = fraud_counts.sort_values(ascending=False)
sorted_fraud_counts

sender_state
Maharashtra       71
Karnataka         69
Uttar Pradesh     52
Delhi             50
Rajasthan         46
Gujarat           43
Tamil Nadu        40
Telangana         39
Andhra Pradesh    35
West Bengal       35
dtype: int64

In [ ]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction id      250000 non-null  object
 1   timestamp           250000 non-null  object
 2   transaction type    250000 non-null  object
 3   merchant_category   250000 non-null  object
 4   amount (INR)        250000 non-null  int64
 5   transaction_status  250000 non-null  object
 6   sender_age_group    250000 non-null  object
 7   receiver_age_group  250000 non-null  object
 8   sender_state        250000 non-null  object
 9   sender_bank         250000 non-null  object
 10  receiver_bank       250000 non-null  object
 11  device_type         250000 non-null  object
 12  network_type        250000 non-null  object
 13  fraud_flag          250000 non-null  int64
 14  hour_of_day         250000 non-null  int64
 15  day_of_week         250000 non-null  object
 16  is_weekend          250000 non-null  int64
dtypes: int64(4), object(13)
memory usage: 32.4+ MB

In [ ]:
df.groupby('device_type')['transaction type'].value_counts()

device_type  transaction type
Android      P2P                 84336
             P2M                 65998
             Bill Payment        28056
             Recharge             9387
Web          P2P                  5635
             P2M                  4393
             Bill Payment         1925
             Recharge              657
iOS          P2P                 22474
             P2M                 17269
             Bill Payment         7387
             Recharge             2483
Name: count, dtype: int64

In [ ]:
df['amount (INR)'].mean()

np.float64(1311.756036)

In [ ]:
df['amount (INR)'].max()

42099

In [ ]:
df['amount (INR)'].min()

10

In [ ]:
df.groupby('sender_bank')['transaction_status'].value_counts(normalize = True)*100

sender_bank  transaction_status
Axis         SUCCESS               95.052312
             FAILED                 4.947688
HDFC         SUCCESS               95.176737
             FAILED                 4.823263
ICICI        SUCCESS               94.964560
             FAILED                 5.035440
IndusInd     SUCCESS               95.046280
             FAILED                 4.953720
Kotak        SUCCESS               95.017971
             FAILED                 4.982029
PNB          SUCCESS               95.105428
             FAILED                 4.894572
SBI          SUCCESS               95.063245
             FAILED                 4.936755
Yes Bank     SUCCESS               94.895414
             FAILED                 5.104586
Name: proportion, dtype: float64

In [ ]:
df[df['fraud_flag']== 1]

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
740,TXN0000000741,2024-10-30 17:37:20,Recharge,Healthcare,361,SUCCESS,18-25,18-25,Karnataka,SBI,ICICI,Android,5G,1,17,Wednesday,0
1228,TXN0000001229,2024-06-22 00:21:52,P2P,Fuel,479,SUCCESS,26-35,36-45,Karnataka,SBI,HDFC,iOS,4G,1,0,Saturday,1
2777,TXN0000002778,2024-06-12 19:46:25,P2P,Food,162,SUCCESS,18-25,36-45,Gujarat,PNB,ICICI,iOS,4G,1,19,Wednesday,0
3761,TXN0000003762,2024-01-30 19:57:42,P2M,Transport,754,SUCCESS,26-35,36-45,Karnataka,ICICI,SBI,Android,5G,1,19,Tuesday,0
3962,TXN0000003963,2024-11-28 21:36:02,P2P,Healthcare,402,SUCCESS,26-35,36-45,Maharashtra,Yes Bank,Kotak,Web,4G,1,21,Thursday,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247717,TXN0000247718,2024-09-29 07:32:05,P2M,Grocery,356,SUCCESS,26-35,26-35,Rajasthan,SBI,IndusInd,Android,WiFi,1,7,Sunday,1
247880,TXN0000247881,2024-01-18 17:32:56,P2P,Other,450,SUCCESS,26-35,36-45,Maharashtra,Axis,Kotak,Android,4G,1,17,Thursday,0
248661,TXN0000248662,2024-11-21 19:26:08,P2M,Food,152,SUCCESS,18-25,46-55,Karnataka,Kotak,HDFC,Android,4G,1,19,Thursday,0
248716,TXN0000248717,2024-12-19 19:45:07,P2P,Fuel,457,SUCCESS,18-25,26-35,Gujarat,Axis,HDFC,Android,4G,1,19,Thursday,0
249181,TXN0000249182,2024-04-27 19:38:45,Bill Payment,Grocery,1443,FAILED,26-35,26-35,Rajasthan,PNB,IndusInd,Android,4G,1,19,Saturday,1

Weekend vs Weekday: Success Rate of UPI Transactions

In [ ]:
successful_transactions = df[df['transaction_status']=='SUCCESS'].groupby('is_weekend').size()
total_transactions = successful_transactions.sum()
successful_transactions_percentage = (successful_transactions/total_transactions)*100
successful_transactions_percentage

is_weekend
0    71.507508
1    28.492492
dtype: float64

Most Fraudulent Day of the Week in UPI Transactions

In [ ]:
df[df['fraud_flag']==1].groupby('day_of_week').size().sort_values(ascending = False)

day_of_week
Sunday       75
Wednesday    75
Thursday     72
Monday       71
Saturday     68
Friday       61
Tuesday      58
dtype: int64

Most Frequently Used Merchant Categories by Age Group

In [ ]:
df.groupby('sender_age_group')['merchant_category'].value_counts()

sender_age_group  merchant_category
18-25             Grocery              12434
                  Food                  9381
                  Shopping              7538
                  Fuel                  6248
                  Other                 6182
                  Utilities             5442
                  Transport             5090
                  Entertainment         4922
                  Healthcare            3179
                  Education             1929
26-35             Grocery              17487
                  Food                 13152
                  Shopping             10327
                  Fuel                  8737
                  Other                 8676
                  Utilities             7931
                  Transport             7102
                  Entertainment         7058
                  Healthcare            4360
                  Education             2602
36-45             Grocery              12563
                  Food                  9309
                  Shopping              7446
                  Fuel                  6411
                  Other                 6345
                  Utilities             5642
                  Entertainment         5104
                  Transport             4857
                  Healthcare            3231
                  Education             1965
46-55             Grocery               4971
                  Food                  3742
                  Shopping              3068
                  Other                 2432
                  Fuel                  2391
                  Utilities             2179
                  Transport             2063
                  Entertainment         2009
                  Healthcare            1242
                  Education              744
56+               Grocery               2511
                  Food                  1880
                  Shopping              1493
                  Fuel                  1276
                  Other                 1193
                  Utilities             1144
                  Entertainment         1010
                  Transport              993
                  Healthcare             651
                  Education              358
Name: count, dtype: int64

In [ ]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

Maximum Fraudulent Transaction Amount by Transaction Type

In [ ]:
df[df['fraud_flag']==1].groupby('transaction type')['amount (INR)'].max().sort_values(ascending= False)

transaction type
P2M             17718
P2P             12071
Bill Payment     9879
Recharge         5072
Name: amount (INR), dtype: int64

Most Used Devices by Sender Age Groups

In [ ]:
df.groupby('sender_age_group')['device_type'].value_counts()

sender_age_group  device_type
18-25             Android        46848
                  iOS            12338
                  Web             3159
26-35             Android        65466
                  iOS            17482
                  Web             4484
36-45             Android        47288
                  iOS            12442
                  Web             3143
46-55             Android        18724
                  iOS             4898
                  Web             1219
56+               Android         9451
                  iOS             2453
                  Web              605
Name: count, dtype: int64

Most Used Devices by Receiver Age Groups

In [ ]:
df.groupby('receiver_age_group')['device_type'].value_counts()

receiver_age_group  device_type
18-25               Android        47068
                    iOS            12466
                    Web             3077
26-35               Android        66124
                    iOS            17274
                    Web             4466
36-45               Android        46587
                    iOS            12364
                    Web             3200
46-55               Android        18549
                    iOS             5011
                    Web             1263
56+                 Android         9449
                    iOS             2498
                    Web              604
Name: count, dtype: int64

Transaction Success Rate by Sender State (%)

In [ ]:
ts_success = df[df['transaction_status']=='SUCCESS'].groupby('sender_state').size()
total_ts = df.groupby('sender_state').size()
ts_success_percentage = (ts_success/total_ts)*100
ts_success_percentage

sender_state
Andhra Pradesh    95.001500
Delhi             95.026136
Gujarat           95.219580
Karnataka         95.137115
Maharashtra       95.078419
Rajasthan         95.205445
Tamil Nadu        94.883116
Telangana         95.293069
Uttar Pradesh     94.781743
West Bengal       94.957941
dtype: float64

Top Bank by Number of Transactions in Each Sender's State

In [ ]:
df.groupby('sender_state')['sender_bank'].value_counts().groupby(level=0).head(1).sort_values(ascending=False)

sender_state    sender_bank
Maharashtra     SBI            9490
Uttar Pradesh   SBI            7562
Karnataka       SBI            7409
Tamil Nadu      SBI            6312
Delhi           SBI            6158
Telangana       SBI            5544
Andhra Pradesh  SBI            5134
West Bengal     SBI            5104
Rajasthan       SBI            5039
Gujarat         SBI            4941
Name: count, dtype: int64

Top Bank by Number of Transactions in Each Receiver's State

In [ ]:
df.groupby('sender_state')['receiver_bank'].value_counts().groupby(level=0).head(1).sort_values(ascending=False)

sender_state    receiver_bank
Maharashtra     SBI              9254
Karnataka       SBI              7543
Uttar Pradesh   SBI              7533
Tamil Nadu      SBI              6386
Delhi           SBI              6189
Telangana       SBI              5587
West Bengal     SBI              5076
Andhra Pradesh  SBI              4983
Gujarat         SBI              4962
Rajasthan       SBI              4865
Name: count, dtype: int64

Total number of transactions categorywise (SUCCESS & FAILED)

In [ ]:
df.groupby('merchant_category')['transaction_status'].value_counts().sort_values(ascending=False)

merchant_category  transaction_status
Grocery            SUCCESS               47463
Food               SUCCESS               35588
Shopping           SUCCESS               28353
Fuel               SUCCESS               23859
Other              SUCCESS               23598
Utilities          SUCCESS               21252
Transport          SUCCESS               19148
Entertainment      SUCCESS               19113
Healthcare         SUCCESS               12051
Education          SUCCESS                7199
Grocery            FAILED                 2503
Food               FAILED                 1876
Shopping           FAILED                 1519
Other              FAILED                 1230
Fuel               FAILED                 1204
Utilities          FAILED                 1086
Entertainment      FAILED                  990
Transport          FAILED                  957
Healthcare         FAILED                  612
Education          FAILED                  399
Name: count, dtype: int64

Most Fraud-Prone Merchant Categories (Ranked by Fraud Count)

In [ ]:
df[df['fraud_flag']==1].groupby('merchant_category').size().sort_values(ascending=False)

merchant_category
Grocery          94
Food             73
Shopping         62
Other            50
Fuel             48
Transport        43
Entertainment    40
Utilities        33
Healthcare       21
Education        16
dtype: int64

In [ ]:
df[df['fraud_flag']== 1].groupby('sender_age_group').size().sort_values(ascending=False)

sender_age_group
26-35    163
18-25    143
36-45    116
46-55     31
56+       27
dtype: int64

In [ ]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

Average Transaction Amount by Transaction Type (Descending Order)

In [ ]:
df.groupby('transaction type')['amount (INR)'].mean().sort_values(ascending=False)

transaction type
P2M             1320.072633
P2P             1308.681115
Bill Payment    1308.492373
Recharge        1290.895745
Name: amount (INR), dtype: float64